name: EvergreenLeaderboards
version: '${version}'
main: evergreen.Leaderboards
api-version: '1.21'
author: Dypel
description: Leaderboard system with time-based tracking
depend: [PlaceholderAPI]

commands:
  evergreenlb:
    description: Main EvergreenLeaderboards command
    usage: /evergreenlb <reload|info|top>

permissions:
  evergreen.leaderboards.admin:
    description: Allows access to all EvergreenLeaderboards admin commands
    default: op

  evergreen.leaderboards.top:
    description: Allows viewing leaderboard tops
    default: true

  evergreen.leaderboards.ignore:
    description: Prevents player from being tracked in leaderboards
    default: false