name: PerchLeaderboards
version: '${version}'
main: me.perch.Leaderboards
api-version: '1.21'
author: Dypel
description: Leaderboard system with time-based tracking
depend: [PlaceholderAPI]

commands:
  perchlb:
    description: Main PerchLeaderboards command
    usage: /perchlb <reload|info|top>

permissions:
  perchlb.admin:
    description: Allows access to all PerchLeaderboards admin commands
    default: op

  perchlb.top:
    description: Allows viewing leaderboard tops
    default: true